"""add kraken credentials to users

Revision ID: eccc293d6dc0
Revises: 0001_initial
Create Date: 2026-09-18 19:18:06.918722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eccc293d6dc0'
down_revision = '0001_initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('kraken_api_key_encrypted', sa.String(), nullable=True))
    op.add_column('users', sa.Column('kraken_api_secret_encrypted', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'kraken_api_secret_encrypted')
    op.drop_column('users', 'kraken_api_key_encrypted')
    # ### end Alembic commands ###
